server:
  port: 8080
  servlet:
    context-path: /aws
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console.enabled: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    schemas: public
    enabled: true
    fail-on-missing-locations: false
