name: 'Build and Push'

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
        
          - name: Log in to the github Container registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
            
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v4
            
          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./docker/Dockerfile
              load: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
      
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        
        # Login to ec2 and rerun docker apps to pull the latest images
        - name: Login to ec2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_KEY }}
            port: ${{ secrets.EC2_PORT }}
            script: |
              cd /home/${{ secrets.EC2_USERNAME }}
              docker-compose pull
              docker-compose up -d
        
