name: 'Docker Build and Push'

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
        
          - name: Log in to the github Container registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
              
          - name: Log in to Docker Hub
            uses: docker/login-action@v2
            with:
              registry: docker.io
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
            
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v4
            
          - name: Build and push Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              file: ./docker/Dockerfile
              load: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
      
